update pdf_templates directory
TIS2023-FMFI/pracovne-cesty pull request #47
Opened 2023-12-21 12:23 UTC by ihorbaltsat

2023-12-23 00:42 UTC, Mcibula requested changes

2023-12-23 00:42 UTC, Mcibula commented on src/storage/app/pdf_templates/Sprava_zo_zahranicnej_sluzobnej_cesty.pdf
Zaloha za cestu sa premenovala, lebo tam bola chyba, uz sa vola `advance_expense`. Ako ak sa ti chce, mozes to premenovat, ale ak nie, tak sa nic nedeje, nejako sa to namapuje na to.

2023-12-23 00:42 UTC, Mcibula commented on src/storage/app/pdf_templates/dohoda_o_poskytnuti_cestovnych_nahrad.pdf
Nie som si isty, ale pri kazdom prinose by mal byt aj textovy detail. @silviabielikova, nevies nahodou, prosim, ci takto?

2023-12-23 09:18 UTC, ihorbaltsat commented on src/storage/app/pdf_templates/Kontrolny_list_TSP_01022023.pdf
Ten font sa tam prisposobuje podla dlzky textu, ale ked to potrebujeme na viac riadkov, tak to mozem spravit

2023-12-24 21:47 UTC, Mcibula requested changes
Prepac, ze nechavam feedback aj v takyto sviatocny den, len som mal chvilku cas, tak som to pozrel. Kludne sa venuj tomu, ked budes mat cas, no pressure.

2023-12-24 21:47 UTC, Mcibula commented on src/storage/app/pdf_templates/Kontrolny_list_TSP_01022023.pdf
Super, vdaka

2023-12-24 21:57 UTC, ihorbaltsat commented on src/nbproject/private/config.properties
hej hej, to som si všimol, lenže čakám že možno to budem ešte opravovať naďalej a vymažem to. a ospravedlňujem’sa že som to vôbec tam pridal a ďakujem za ten článok a za feedback.

2023-12-24 22:07 UTC, Mcibula commented on src/nbproject/private/config.properties
Uplne v pohode, netrap sa tym, to sa stava :slightly_smiling_face:

2023-12-25 19:03 UTC, Mcibula approved these changes

2023-12-25 19:04 UTC, Mcibula commented
Je to fajn, len este to asi nemerguj, nech si to mozu pozriet aj ostatni.

2023-12-26 00:05 UTC, samoslavik45 approved these changes
Za mňa všetko v pohode, pekná práca.

2023-12-26 10:39 UTC, silviabielikova commented on src/storage/app/pdf_templates/dohoda_o_poskytnuti_cestovnych_nahrad.pdf
hej, zatial ratame s tym, ze su tam textove detaily, takze by ich tam bolo treba pridat (kludne nechat checkbox + textovy detail)

2023-12-26 10:40 UTC, silviabielikova requested changes
pridat textove detaily pre prinosy pre fakultu a  a este v sprave zo zahranicnej PC chyba pole na vycislenie preplatenych vydavkov v pripade pozvania, inak super

2024-01-03 15:33 UTC, silviabielikova approved these changes
super, moze sa to mergnut

2024-01-05 22:40 UTC, Mcibula commented
Teraz by to uz malo byt v poriadku a bez konfliktov, mozes mergnut @ihorbaltsat .

2024-01-06 12:27 UTC, merged