Controllers templates
TIS2023-FMFI/pracovne-cesty pull request #48
Opened 2023-12-21 15:12 UTC by ihorbaltsat

2023-12-25 00:38 UTC, Mcibula requested changes
Tu tiez treba spravit untrack tych files v `src/nbproject/` a tiez aj vsetkych pdf templates, lebo tie uz mame v inom PR, tak aby nam nevznikali konflikty. Da sa to spravit zase tak, ze odstranis u seba `nbproject/` a cely adresar `pdf_templates` a commitnes a pushnes sem tie zmeny.

Ale tie controllery vyzeraju dost dobre.

2023-12-25 00:38 UTC, Mcibula commented on .gitignore
Tento `.gitignore` sa moze vratit do povodneho stavu, lebo v `main` uz mame taky s `nbproject/`

2023-12-25 21:38 UTC, Mcibula requested changes
Dokumentacne komentare metod, ktore su vo formate
```php
    //Returning view with details from all trips
    public function index() {
        return view();
    }
```
by som len upravil na standardne PHPDoc komentare, ktore vyzeraju takto:
```php
    /**
     * Returning view with details from all trips
     */
    public function index() {
        return view();
    }
```

2023-12-26 00:07 UTC, samoslavik45 approved these changes

2023-12-26 10:20 UTC, silviabielikova approved these changes
myslim, ze pre zaciatok ako kostra to staci, bude sa dorabat podla potreby, je to fajnn

2023-12-26 14:28 UTC, Mcibula approved these changes
Super

2023-12-26 15:56 UTC, merged